Dism /Online /Disable-Feature /FeatureName:"Internet-Explorer-Optional-amd64"
Dism /Online /Disable-Feature /FeatureName:"Printing-PrintToPDFServices-Features"
Dism /Online /Disable-Feature /FeatureName:"Printing-XPSServices-Features"
Dism /Online /Disable-Feature /FeatureName:"Printing-Foundation-Feature"
Dism /Online /Disable-Feature /FeatureName:"Remote-Differencial-Compression-API-Support"
Dism /Online /Disable-Feature /FeatureName:"SMB1Protocol"
Dism /Online /Disable-Feature /FeatureName:"Printing-Foundation-InternetPrinting-Client"
